### ISSUE TITLE
Error: class uri 'eventlet' invalid or not found

### ISSUE THREAD

**Issue by ingolevin** [nickfarrow/SatSale#8]
Hi, 
It appears that Eventlet 0.30.3 removed `eventlet.wsgi.ALREADY_HANDLED` which is used by gunicorn

See: https://github.com/eventlet/eventlet/issues/702

The pinned version `eventlet==0.31.0` in requirements.txt causes this error for me:

```
Error: class uri 'eventlet' invalid or not found: 

[Traceback (most recent call last):
  File "/mnt/c/Users/ingo/Documents/Code/SatSale/.venv/lib/python3.6/site-packages/gunicorn/util.py", line 99, in load_class
    mod = importlib.import_module('.'.join(components))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/ingo/Documents/Code/SatSale/.venv/lib/python3.6/site-packages/gunicorn/workers/geventlet.py", line 23, in <module>
    from eventlet.wsgi import ALREADY_HANDLED as EVENTLET_ALREADY_HANDLED
ImportError: cannot import name 'ALREADY_HANDLED'
```

### Workaround
`pip install --upgrade eventlet==0.30.2`

**Comment by dergigi** [comment]
It seems like the `eventlet` dependency was removed with 4312c7682113d138483722e50eccdf4a314805a6 and now the error pops up again (at least it did for me).

**Comment by dergigi** [comment]
Running with `nohup gunicorn -w 1 -b 0.0.0.0:8000 satsale:app > log.txt 2>&1 &` worked, I guess the README has to be updated.

**Comment by nickfarrow** [comment]
> Running with `nohup gunicorn -w 1 -b 0.0.0.0:8000 satsale:app > log.txt 2>&1 &` worked, I guess the README has to be updated.

Good call. I recently had some issues with RPC connection no longer working after some time when not using `eventlet`, 

Can confirm that I have been running with the command above just fine. Thank you Gigi, and for trying it out. Please let me know of any suggestions/feedback. (or pull requests!)
Updated README.md: https://github.com/nickfarrow/SatSale/commit/eb2beade6d5fc2f0998abda7e87bb28e35b8f97d
